version: '3'
services:
  rabbitmq-master-server:
    environment:
      RABBITMQ_ERLANG_COOKIE: secret
    hostname: rabbitmq-master-server
    image: zerpetfakename/rabbitmq-cluster:3.6
    ports:
    - 5672:5672
    - 15672:15672
  rabbitmq-worker-server:
    environment:
      CLUSTER_WITH: 'rabbit@rabbitmq-master-server'
      RABBITMQ_ERLANG_COOKIE: secret
    hostname: rabbitmq-worker-server
    image: zerpetfakename/rabbitmq-cluster:3.6
    ports:
    - 5673:5672
    - 15673:15672
  rabbitmq-ram-server:
    environment:
      CLUSTER_WITH: 'rabbit@rabbitmq-master-server'
      RABBITMQ_ERLANG_COOKIE: secret
      ENABLE_RAM: 'true'
    hostname: rabbitmq-ram-server
    image: zerpetfakename/rabbitmq-cluster:3.6
    ports:
    - 5674:5672
    - 15674:15672   
